spring.application.name=api-gateway
server.port=8080

user.service.url=http://localhost:8081
movie.service.url=http://localhost:8082
rating.service.url=http://localhost:8083
recommendation.service.url=http://localhost:8084