spring.application.name=api-gateway

server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat

jwt.secret=${JWT_SECRET}

user.service.url=http://user-service:8081
movie.service.url=http://movie-service:8082
rating.service.url=http://rating-service:8083
recommendation.service.url=http://recommendation-service:8084